name: FrontendCI
on:
  push:
    paths:
      - "web/**/*"
      - ".github/workflows/frontend.yaml"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.3'

      - name: Install dependencies
        working-directory: ./web
        run: npm i

      - name: Test
        working-directory: ./web
        run: npx tsc && npm run test

      - name: Build
        working-directory: ./web
        run: npm run build:prod

      - name: Deploy
        uses: jakejarvis/s3-sync-action@master
        if: github.ref == 'refs/heads/master'
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.FRONTEND_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-southeast-2"
          SOURCE_DIR: './web/build'

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        if: github.ref == 'refs/heads/master'
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DEPLOYMENT_ID }}
          PATHS: '/*'
          AWS_REGION: "ap-southeast-2"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
