name: InfraCI
on:
  push:
    paths:
      - "infra/**/*"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./infra
        run: npm i

      - name: Test CDK
        working-directory: ./infra
        run: npm run test

      - name: Build CDK
        working-directory: ./infra
        run: npm run build

      - name: Deploy CDK
        uses: youyo/aws-cdk-github-actions@v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/deploy')
        with:
          working_dir: 'infra'
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-2'
