name: CI
on: [ push, pull_request ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.3'

      - name: Install dependencies
        working-directory: ./web
        run: npm i

      - name: Test Frontend
        working-directory: ./web
        run: npx tsc && npm run test

      - name: Build
        working-directory: ./web
        run: npm run build
