name: CI
on: [ pull_request ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.3'

      - name: Install dependencies
        working-directory: ./web
        run: npm i

      - name: Test Frontend
        working-directory: ./web
        run: npx tsc && npm run test

      - name: Build
        working-directory: ./web
        run: npm run build

      - name: Deploy Frontend
        uses: reggionick/s3-deploy@v3
#        if: github.ref == 'refs/heads/master'
        with:
          folder: ./web/build
          bucket: ${{ secrets.FRONTEND_S3_BUCKET }}
          bucket-region: ap-southeast-2
          dist-id: ${{ secrets.CLOUDFRONT_DEPLOYMENT_ID }}
          invalidation: /*
          delete-removed: true   # We want to remove everything else form the s3 bucket

      - name: Test Backend
        run: pip install -r requirements.txt && python -m unittest

      - name: Run Pylint
        run: pylint-fail-under --rcfile .pylintrc --fail_under 9.75 $(git ls-files --directory app)
